// 小红书卡片内置主题：每个主题覆盖编辑器 CSS 变量，实现卡片配色
import type { XhsTheme } from "./types";

export const XHS_THEMES: XhsTheme[] = [
  {
    // 默认主题：不覆盖任何 CSS 变量，完全继承编辑器文档主题的配色，
    // 保证卡片渲染颜色与文档渲染颜色完全一致；其余主题为小红书专属配色。
    id: "default",
    name: "默认",
    vars: {},
  },
  {
    id: "cream",
    name: "奶油白",
    vars: {
      "--bg-primary": "#fffaf3",
      "--bg-secondary": "#f7efe3",
      "--bg-surface": "#fbf5ec",
      "--bg-code": "#f5ecdf",
      "--bg-code-inline": "rgba(224, 86, 74, 0.10)",
      "--text-primary": "#3d3833",
      "--text-secondary": "#8a8076",
      "--accent": "#e0564a",
      "--accent-rgb": "224, 86, 74",
      "--accent-hover": "#c94a3f",
      "--border": "#ecdfcd",
      "--danger": "#dc2626",
      "--text-strong": "#c23d5a",
    },
  },
  {
    id: "mint",
    name: "薄荷绿",
    vars: {
      "--bg-primary": "#f6fcf9",
      "--bg-secondary": "#e6f4ec",
      "--bg-surface": "#eef8f2",
      "--bg-code": "#ecf6f0",
      "--bg-code-inline": "rgba(78, 178, 137, 0.10)",
      "--text-primary": "#22332b",
      "--text-secondary": "#6b8175",
      "--accent": "#2f9e6e",
      "--accent-rgb": "47, 158, 110",
      "--accent-hover": "#25855c",
      "--border": "#cfe6d9",
      "--danger": "#e0564a",
      "--text-strong": "#1a7f5a",
    },
  },
  {
    id: "mocha",
    name: "莫兰迪",
    vars: {
      "--bg-primary": "#f7f5f2",
      "--bg-secondary": "#ede9e4",
      "--bg-surface": "#f2efeb",
      "--bg-code": "#eeeae5",
      "--bg-code-inline": "rgba(122, 108, 94, 0.10)",
      "--text-primary": "#3f3a35",
      "--text-secondary": "#8c8277",
      "--accent": "#8c7a6b",
      "--accent-rgb": "140, 122, 107",
      "--accent-hover": "#74604f",
      "--border": "#ddd6ce",
      "--danger": "#c94a3f",
      "--text-strong": "#a3604f",
    },
  },
  {
    id: "ink",
    name: "极简黑",
    vars: {
      "--bg-primary": "#121212",
      "--bg-secondary": "#1b1b1b",
      "--bg-surface": "#242424",
      "--bg-code": "#1e1e1e",
      "--bg-code-inline": "rgba(255, 255, 255, 0.08)",
      "--text-primary": "#f2f2f2",
      "--text-secondary": "#9a9a9a",
      "--accent": "#ffffff",
      "--accent-rgb": "255, 255, 255",
      "--accent-hover": "#dddddd",
      "--border": "#2c2c2c",
      "--danger": "#ff6b6b",
      "--text-strong": "#ffd24a",
    },
  },
  {
    id: "lavender",
    name: "渐变紫",
    vars: {
      "--bg-primary": "#faf7ff",
      "--bg-secondary": "#f1e9ff",
      "--bg-surface": "#f5efff",
      "--bg-code": "#f2ecff",
      "--bg-code-inline": "rgba(124, 58, 237, 0.10)",
      "--text-primary": "#2e2440",
      "--text-secondary": "#7a6f90",
      "--accent": "#7c3aed",
      "--accent-rgb": "124, 58, 237",
      "--accent-hover": "#6d28d9",
      "--border": "#e4d9f7",
      "--danger": "#dc2626",
      "--text-strong": "#9d3ad1",
    },
  },
  {
    id: "ocean",
    name: "海盐蓝",
    vars: {
      "--bg-primary": "#f5fbff",
      "--bg-secondary": "#e4f2fb",
      "--bg-surface": "#ecf6fd",
      "--bg-code": "#e9f4fc",
      "--bg-code-inline": "rgba(8, 145, 178, 0.10)",
      "--text-primary": "#153243",
      "--text-secondary": "#5f7a8a",
      "--accent": "#0891b2",
      "--accent-rgb": "8, 145, 178",
      "--accent-hover": "#0e7490",
      "--border": "#cde7f3",
      "--danger": "#e0564a",
      "--text-strong": "#0b7285",
    },
  },
  {
    id: "blush",
    name: "樱花粉",
    vars: {
      "--bg-primary": "#fff7f9",
      "--bg-secondary": "#fdeaf0",
      "--bg-surface": "#fdf1f5",
      "--bg-code": "#fcebf1",
      "--bg-code-inline": "rgba(244, 114, 150, 0.12)",
      "--text-primary": "#3d2f35",
      "--text-secondary": "#8f7780",
      "--accent": "#f4719a",
      "--accent-rgb": "244, 113, 154",
      "--accent-hover": "#e04d80",
      "--border": "#f5d3de",
      "--danger": "#dc2626",
      "--text-strong": "#d6477a",
    },
  },
  {
    id: "sunset",
    name: "落日橙",
    vars: {
      "--bg-primary": "#fff9f2",
      "--bg-secondary": "#fdeedd",
      "--bg-surface": "#fef4e8",
      "--bg-code": "#fbf0e2",
      "--bg-code-inline": "rgba(245, 158, 11, 0.12)",
      "--text-primary": "#3e3329",
      "--text-secondary": "#8a7a68",
      "--accent": "#f59e0b",
      "--accent-rgb": "245, 158, 11",
      "--accent-hover": "#d97706",
      "--border": "#f3ddbb",
      "--danger": "#dc2626",
      "--text-strong": "#d94f2b",
    },
  },
];

export function getXhsTheme(id: string): XhsTheme {
  return XHS_THEMES.find((t) => t.id === id) ?? XHS_THEMES[0];
}
